In [129]:
from typing import Dict, Text
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_recommenders as tfrs

In [130]:
import sqlite3
connection = sqlite3.connect('db.sqlite3')
cursor = connection.cursor()
statement = '''select * from store_product'''
cursor.execute(statement)
products = cursor.fetchall()
products = pd.DataFrame(products)
products.columns = ['pid', 'pname', 'section', 'subsection', 'price', 'company', 'desc', 'url1', 'url2', 'url3']
products

pid                                pname      section subsection  price  \
0    1        HP 15s 12th Gen Intel Core i5  Electronics     Laptop  55000   
1    5  Acer Extensa Intel Core i3 11th Gen  Electronics     Laptop  33500   
2    6       Hp 14S, 11Th Gen Intel Core I3  Electronics     Laptop  41000   
3    7                Samsung Galaxy M33 5G  Electronics     Mobile  20000   
4    8             Samsung Galaxy S21 FE 5G  Electronics     Mobile  50000   
5    9                        MOTOROLA e32s  Electronics     Mobile  12000   
6   10      Symbol Men's Regular Polo Shirt      Fashion    Tshirts    350   
7   11           Nike Gravity Running Shoes       Sports      Shoes  14344   

    company                                               desc  \
0        HP  Processor:Intel Core i5-1235U (up to 4.4 GHz w...   
1      Acer  Fast & easy computing Perfect budget laptop fo...   
2        HP  Do Check Partner offer section for Exciting of...   
3   Samsung  Exynos 1280 Octa Core 2.4GHz 5nm Processor wit...   
4   Samsung  Pro-grade Camera with AI Single Take, Portrait...   
5  MOTOROLA  4 GB RAM | 64 GB ROM | Expandable Upto 1 TB 16...   
6    Symbol  Care Instructions: Machine wash cold with simi...   
7      Nike  Closure: Lace-Up Shoe Width: Medium WMNS NIKE ...   

                                                url1  \
0  https://m.media-amazon.com/images/I/419CsUXodA...   
1  https://m.media-amazon.com/images/I/41uXxOM7Xm...   
2  https://m.media-amazon.com/images/I/410cDRJZVv...   
3  https://m.media-amazon.com/images/I/419KF2t1nM...   
4  https://m.media-amazon.com/images/I/413fd9o3Ag...   
5  https://m.media-amazon.com/images/I/41szxWVqHM...   
6  https://m.media-amazon.com/images/I/41q6jpID0k...   
7  https://m.media-amazon.com/images/I/71kZa47SDA...   

                                                url2  \
0  https://m.media-amazon.com/images/I/51qQtOH0Fz...   
1  https://m.media-amazon.com/images/I/41j-GHHuPC...   
2  https://m.media-amazon.com/images/I/51FKw3rl4X...   
3  https://m.media-amazon.com/images/I/41YauqVGKw...   
4  https://m.media-amazon.com/images/I/417tG8acZ-...   
5  https://m.media-amazon.com/images/I/41z3h-G6O6...   
6  https://m.media-amazon.com/images/I/81h32NQvVu...   
7  https://m.media-amazon.com/images/I/71kZa47SDA...   

                                                url3  
0  https://m.media-amazon.com/images/I/512jqnxLJd...  
1  https://m.media-amazon.com/images/I/31ezpDvQR5...  
2  https://m.media-amazon.com/images/I/51YD9IJCWJ...  
3  https://m.media-amazon.com/images/I/51656BNPa3...  
4  https://m.media-amazon.com/images/I/51c8Wr9OaA...  
5  https://m.media-amazon.com/images/I/31k+Sl+ir8...  
6  https://m.media-amazon.com/images/I/313KVv9IxW...  
7  https://m.media-amazon.com/images/I/71kZa47SDA...

In [2]:
from pymongo import MongoClient
import pymongo, urllib
CONNECTION_STRING = "mongodb+srv://Ecommerce:" + urllib.parse.quote("Ecommerce@123") + "@cluster0.xi9cy3b.mongodb.net/Ecommerce?retryWrites=true&w=majority&ssl=true&ssl_cert_reqs=CERT_NONE"
client = MongoClient(CONNECTION_STRING)
db = client['ecommerce']

C:\ProgramData\Anaconda3\lib\site-packages\pymongo\common.py:760: UserWarning: Unknown option ssl_cert_reqs
  warnings.warn(str(exc))


_id  pid                          pname      section  \
0  62d2be0ed64c0d5215fd12fb    1  HP 15s 12th Gen Intel Core i5  Electronics   
1  62d2bfd7d64c0d5215fd12fd    2        ASUS VivoBook 15 (2021)  Electronics   
2  62d2c057d64c0d5215fd12ff    3  Dell New Inspiron 3525 Laptop  Electronics   
3  62d2c10fd64c0d5215fd1302    4          Samsung Galaxy M33 5G  Electronics   
4  62d2c181d64c0d5215fd1304    5                 Redmi 9A Sport  Electronics   

  subsection  price  company  \
0     Laptop  55000       HP   
1     Laptop  26000     Asus   
2     Laptop  31500     Dell   
3     Mobile  19499  Samsung   
4     Mobile   7000    Redmi   

                                                desc  \
0  Processor:Intel Core i5-1235U (up to 4.4 GHz w...   
1  Processor: Intel Celeron N4020, 1.1 GHz base s...   
2  Processor: AMD Athlon Silver 3050U (2.30 GHz u...   
3  Exynos 1280 Octa Core 2.4GHz 5nm Processor wit...   
4  Processor: MediaTek Helio G25 Octa-core; Up to...   

                                                url1  \
0  https://m.media-amazon.com/images/I/419CsUXodA...   
1  https://m.media-amazon.com/images/I/414057taYK...   
2  https://m.media-amazon.com/images/I/41yulPJHC3...   
3  https://m.media-amazon.com/images/I/419KF2t1nM...   
4  https://m.media-amazon.com/images/I/41i7LM0pGw...   

                                                url2  \
0  https://m.media-amazon.com/images/I/51qQtOH0Fz...   
1  https://m.media-amazon.com/images/I/41-3DfIcgi...   
2  https://m.media-amazon.com/images/I/41I-ZLP3AS...   
3  https://m.media-amazon.com/images/I/41YauqVGKw...   
4  https://m.media-amazon.com/images/I/31HFmn2xQH...   

                                                url3  
0  https://m.media-amazon.com/images/I/512jqnxLJd...  
1  https://m.media-amazon.com/images/I/41y7bcUFoV...  
2  https://m.media-amazon.com/images/I/41yOIxFhWo...  
3  https://m.media-amazon.com/images/I/51656BNPa3...  
4  https://m.media-amazon.com/images/I/41tHOrB8lD...

In [131]:
statement = '''select * from store_cartcount'''
cursor.execute(statement)
carts = cursor.fetchall()
carts = pd.DataFrame(carts)
print(carts.shape)
carts.columns = ['id', 'pname', 'count']
carts.head()

(8, 3)


id                           pname  count
0   1        Samsung Galaxy S21 FE 5G      4
1   2           Samsung Galaxy M33 5G      3
2   3   HP 15s 12th Gen Intel Core i5      3
3   4                   MOTOROLA e32s      1
4   5  Hp 14S, 11Th Gen Intel Core I3      2

In [132]:
statement = '''select * from store_viewcount'''
cursor.execute(statement)
views = cursor.fetchall()
views = pd.DataFrame(views)
print(views.shape)
views.columns = ['id', 'pname', 'count']
views.head()

(8, 3)


id                           pname  count
0   1        Samsung Galaxy S21 FE 5G     19
1   2           Samsung Galaxy M33 5G     23
2   3                   MOTOROLA e32s     15
3   4   HP 15s 12th Gen Intel Core i5     21
4   5  Hp 14S, 11Th Gen Intel Core I3     10

In [133]:
statement = '''select * from store_rating'''
cursor.execute(statement)
ratings = cursor.fetchall()
ratings = pd.DataFrame(ratings)
print(ratings.shape)
ratings.columns = ['id', 'userid', 'subsection', 'pname', 'rating']
ratings.head()

(14, 5)


id  userid subsection                          pname  rating
0   1       1     Mobile          Samsung Galaxy M33 5G       4
1   2       3     Mobile                  MOTOROLA e32s       4
2   3       2     Mobile          Samsung Galaxy M33 5G       5
3   4       3     Mobile          Samsung Galaxy M33 5G       4
4   5       1     Laptop  HP 15s 12th Gen Intel Core i5       2

In [134]:
connection.commit()
connection.close()

In [135]:
ratings['userid'] = ratings['userid'].apply(str)
ratings['rating'] = ratings['rating'].astype(float)

In [136]:
ratings = ratings[['pname', 'userid', 'rating']]
ratings.head()

pname userid  rating
0          Samsung Galaxy M33 5G      1     4.0
1                  MOTOROLA e32s      3     4.0
2          Samsung Galaxy M33 5G      2     5.0
3          Samsung Galaxy M33 5G      3     4.0
4  HP 15s 12th Gen Intel Core i5      1     2.0

In [137]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   pname   14 non-null     object 
 1   userid  14 non-null     object 
 2   rating  14 non-null     float64
dtypes: float64(1), object(2)
memory usage: 464.0+ bytes


In [138]:
ratings = tf.data.Dataset.from_tensor_slices(ratings.to_dict(orient='list'))
products = tf.data.Dataset.from_tensor_slices(products.to_dict(orient='list'))

In [84]:
print(ratings)

<TensorSliceDataset element_spec={'pname': TensorSpec(shape=(), dtype=tf.string, name=None), 'userid': TensorSpec(shape=(), dtype=tf.string, name=None), 'rating': TensorSpec(shape=(), dtype=tf.float32, name=None)}>


If any extra columns are present in the dataframe just picking out required columns for recommendation

In [85]:
def print_elements(dataset, k):
    count = 0
    for i in dataset:
        if count < k:
            print(i)
            count +=1
        else:
            break

In [139]:
ratings = ratings.map(lambda x: {
    'product_title': x['pname'],
    'user_id': x['userid'],
    'user_rating': x['rating'],
})
products = products.map(lambda x: x['pname'])

In [87]:
print_elements(ratings, 10)
print_elements(products, 10)

{'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Samsung Galaxy M33 5G'>, 'user_id': <tf.Tensor: shape=(), dtype=string, numpy=b'1'>, 'user_rating': <tf.Tensor: shape=(), dtype=float32, numpy=4.0>}
{'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'MOTOROLA e32s'>, 'user_id': <tf.Tensor: shape=(), dtype=string, numpy=b'3'>, 'user_rating': <tf.Tensor: shape=(), dtype=float32, numpy=4.0>}
{'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Samsung Galaxy M33 5G'>, 'user_id': <tf.Tensor: shape=(), dtype=string, numpy=b'2'>, 'user_rating': <tf.Tensor: shape=(), dtype=float32, numpy=5.0>}
{'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Samsung Galaxy M33 5G'>, 'user_id': <tf.Tensor: shape=(), dtype=string, numpy=b'3'>, 'user_rating': <tf.Tensor: shape=(), dtype=float32, numpy=4.0>}
{'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'HP 15s 12th Gen Intel Core i5'>, 'user_id': <tf.Tensor: shape=(), dtype=string, numpy=b'1'>, 'user_rat

We are using tf.data.Dataset format instead of dataframe as it is easy to use for making model we cannot directly find out the shape of data hence using this function to find out shape of dataset

In [42]:
def dataset_shapes(dataset):
    try:
        return [x.get_shape().as_list() for x in dataset._tensors]
    except TypeError:
        return dataset._tensors.get_shape().as_list()

In [140]:
tf.random.set_seed(42)
# ratings_shape = dataset_shapes(ratings)
ratings_shape = len(ratings)

Shuffling the rows from dataset and splitting it into train and test data. 80% for training and 20% for testing

In [141]:
ratings_shuffled = ratings.shuffle(ratings_shape, seed=42, reshuffle_each_iteration=False)
ratings_train = ratings_shuffled.take(round(0.8 * ratings_shape))
ratings_test = ratings_shuffled.skip(round(0.8 * ratings_shape)).take(round(0.2 * ratings_shape))

Making batches of dataset and also finding unique distinct values from particular dataset for finding out vocabulary inside the given data set which eventually assists in training the model.

In [ ]:
# For production purpose
# product_titles = products.batch(round(0.01 * ratings_shape))
# unique_product_titles = np.unique(np.concatenate(product_titles))

In [142]:
product_titles = products.batch(4)
print(list(product_titles.as_numpy_iterator()))
unique_product_titles = np.unique(np.concatenate(list(product_titles)))

[array([b'HP 15s 12th Gen Intel Core i5',
       b'Acer Extensa Intel Core i3 11th Gen',
       b'Hp 14S, 11Th Gen Intel Core I3', b'Samsung Galaxy M33 5G'],
      dtype=object), array([b'Samsung Galaxy S21 FE 5G', b'MOTOROLA e32s',
       b"Symbol Men's Regular Polo Shirt", b'Nike Gravity Running Shoes'],
      dtype=object)]


In [91]:
user_ids_ratings = ratings.batch(10 * ratings_shape).map(lambda x: x['user_id'])
unique_user_ids_ratings = np.unique(np.concatenate(list(user_ids_ratings)))
print(unique_user_ids_ratings)

[b'1' b'2' b'3' b'4' b'5' b'7']


Model definition for product recommendation using ratings given by the users for products.

In [143]:
class ProductRatingModel(tfrs.models.Model):
    def __init__(self, rating_weight: float, retrieval_weight: float) -> None:
        super().__init__()
        embedding_dimension = 32
        self.product_model: tf.keras.layers.Layer = tf.keras.Sequential([
            tf.keras.layers.StringLookup(vocabulary=unique_product_titles, mask_token=None),
            tf.keras.layers.Embedding(len(unique_product_titles) + 1, embedding_dimension),
        ])

        self.user_model: tf.keras.layers.Layer = tf.keras.Sequential([
            tf.keras.layers.StringLookup(vocabulary=unique_user_ids_ratings, mask_token=None),
            tf.keras.layers.Embedding(len(unique_user_ids_ratings) + 1, embedding_dimension),
        ])

        self.rating_model = tf.keras.Sequential([
            tf.keras.layers.Dense(256, activation='relu'),
            tf.keras.layers.Dense(128, activation='relu'),
            tf.keras.layers.Dense(1),
        ])

        self.rating_task: tf.keras.layers.Layer = tfrs.tasks.Ranking(loss=tf.keras.losses.MeanSquaredError(), metrics=[tf.keras.metrics.RootMeanSquaredError()],)

        self.retrieval_task: tf.keras.layers.Layer = tfrs.tasks.Retrieval(metrics=tfrs.metrics.FactorizedTopK(candidates=products.map(self.product_model)))

        self.rating_weight = rating_weight
        self.retrieval_weight = retrieval_weight

    def __call__(self, features: Dict[Text, tf.Tensor]) -> tf.Tensor:
        user_embeddings = self.user_model(features['user_id'])
        product_embeddings = self.product_model(features['product_title'])
        return (user_embeddings, product_embeddings, self.rating_model(tf.concat([user_embeddings, product_embeddings], axis=1)))

    def compute_loss(self, features: Dict[Text, tf.Tensor], training: bool = False) -> tf.Tensor:
        ratings = features.pop('user_rating')
        user_embeddings, product_embeddings, rating_predictions = self(features)
        rating_loss = self.rating_task(labels=ratings, predictions=rating_predictions)
        retrieval_loss = self.retrieval_task(user_embeddings, product_embeddings)
        return self.rating_weight * rating_loss + self.retrieval_weight * retrieval_loss



Finding top 5 products recommended by each model i.e. ratings, carts, view

In [144]:
ratings_model = ProductRatingModel(rating_weight=1.0, retrieval_weight=1.0)
ratings_model.compile(optimizer=tf.keras.optimizers.Adagrad(0.1))

In [145]:
cached_train = ratings_train.shuffle(ratings_shape).batch(4).cache()
cached_test = ratings_test.batch(2).cache()

In [146]:
ratings_model.fit(cached_train, epochs=10)
metrics = ratings_model.evaluate(cached_test, return_dict=True)
print(f"Retrieval top-100 accuracy: {metrics['factorized_top_k/top_100_categorical_accuracy']:.3f}.")
print(f"Ranking RMSE: {metrics['root_mean_squared_error']:.3f}.")

Epoch 1/10


ValueError: in user code:

    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\models\base.py", line 68, in train_step
        loss = self.compute_loss(inputs, training=True)
    File "C:\Users\yashk\AppData\Local\Temp/ipykernel_6488/4186026065.py", line 37, in compute_loss
        retrieval_loss = self.retrieval_task(user_embeddings, product_embeddings)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_file67ei5xe9.py", line 81, in tf__call
        ag__.if_stmt(ag__.ld(compute_metrics), if_body_2, else_body_2, get_state_2, set_state_2, (), 0)
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_file67ei5xe9.py", line 64, in if_body_2
        ag__.if_stmt(ag__.ld(self)._factorized_metrics, if_body, else_body, get_state, set_state, (), 0)
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_file67ei5xe9.py", line 60, in if_body
        ag__.converted_call(ag__.ld(metric_update_ops).append, (ag__.converted_call(ag__.ld(self)._factorized_metrics.update_state, (ag__.ld(query_embeddings), ag__.ld(candidate_embeddings)), None, fscope),), None, fscope)
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_file93chvymw.py", line 21, in tf__update_state
        (top_k_predictions, _) = ag__.converted_call(ag__.ld(self)._candidates, (ag__.ld(query_embeddings),), dict(k=ag__.ld(self)._k), fscope)
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_fileaz5o9aag.py", line 163, in tf__call
        results = ag__.converted_call(ag__.converted_call(ag__.ld(candidates).map, (ag__.ld(top_scores),), dict(num_parallel_calls=ag__.ld(self)._num_parallel_calls), fscope).reduce, (ag__.ld(initial_state), ag__.ld(top_k)), None, fscope)
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_fileaz5o9aag.py", line 48, in top_scores
        scores = ag__.converted_call(ag__.ld(self)._compute_score, (ag__.ld(queries), ag__.ld(candidate_batch)), None, fscope_1)
    File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\layers\factorized_top_k.py", line 319, in _compute_score
        return tf.matmul(queries, candidates, transpose_b=True)

    ValueError: Exception encountered when calling layer "retrieval_4" (type Retrieval).
    
    in user code:
    
        File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\tasks\retrieval.py", line 143, in call  *
            metric_update_ops.append(
        File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\metrics\factorized_top_k.py", line 84, in update_state  *
            top_k_predictions, _ = self._candidates(query_embeddings, k=self._k)
        File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
        File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_fileaz5o9aag.py", line 163, in tf__call
            results = ag__.converted_call(ag__.converted_call(ag__.ld(candidates).map, (ag__.ld(top_scores),), dict(num_parallel_calls=ag__.ld(self)._num_parallel_calls), fscope).reduce, (ag__.ld(initial_state), ag__.ld(top_k)), None, fscope)
        File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_fileaz5o9aag.py", line 48, in top_scores
            scores = ag__.converted_call(ag__.ld(self)._compute_score, (ag__.ld(queries), ag__.ld(candidate_batch)), None, fscope_1)
        File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\layers\factorized_top_k.py", line 319, in _compute_score
            return tf.matmul(queries, candidates, transpose_b=True)
    
        ValueError: Exception encountered when calling layer "streaming_4" (type Streaming).
        
        in user code:
        
            File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\layers\factorized_top_k.py", line 409, in top_scores  *
                scores = self._compute_score(queries, candidate_batch)
            File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\layers\factorized_top_k.py", line 319, in _compute_score  **
                return tf.matmul(queries, candidates, transpose_b=True)
        
            ValueError: Shape must be rank 2 but is rank 1 for '{{node MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=true](MatMul/sequential_19/embedding_15/embedding_lookup/Identity_1, args_1)' with input shapes: [?,32], [32].
        
        
        Call arguments received by layer "streaming_4" (type Streaming):
          • queries=tf.Tensor(shape=(None, 32), dtype=float32)
          • k=100
    
    
    Call arguments received by layer "retrieval_4" (type Retrieval):
      • query_embeddings=tf.Tensor(shape=(None, 32), dtype=float32)
      • candidate_embeddings=tf.Tensor(shape=(None, 32), dtype=float32)
      • sample_weight=None
      • candidate_sampling_probability=None
      • candidate_ids=None
      • compute_metrics=True


In [147]:
brute_force = tfrs.layers.factorized_top_k.BruteForce(ratings_model.user_model)
brute_force.index_from_dataset(products.batch(128).map(lambda title: (title, ratings_model.product_model(title))))

In [148]:
_, titles_based_on_ratings = brute_force(np.array(["42"]), k = 5)
print(f"{titles_based_on_ratings[0]}")

# Instead of 42 need to add the current userid

[b'MOTOROLA e32s' b'Acer Extensa Intel Core i3 11th Gen'
 b'Nike Gravity Running Shoes' b'Hp 14S, 11Th Gen Intel Core I3'
 b"Symbol Men's Regular Polo Shirt"]


As the value inside the list of 5 recommendation is in the form of tensor So to fetch it in the normal string use -->
data = titles_based_on_ratings[0] gives 1st tensor recommended product

data = titles_based_on_ratings[0][0] gives the product title in the form of tensor numpy

data = titles_based_on_ratings[0][0].numpy() provides the extracted string i.e. b'string'

in order to remove this "b" data = data.decode() now this gets converted back to normal python string

while suppose while comparing we need to convert normal python string to tensor string i.e. 'string' -> b'string' use data = data.encode()

In [116]:
popular_cart_products = carts.sort_values(by=['count'], ascending=False)
popular_cart_products.head(10)

id                                pname  count
0   1             Samsung Galaxy S21 FE 5G      4
1   2                Samsung Galaxy M33 5G      3
2   3        HP 15s 12th Gen Intel Core i5      3
6   7           Nike Gravity Running Shoes      3
4   5       Hp 14S, 11Th Gen Intel Core I3      2
7   8      Symbol Men's Regular Polo Shirt      2
3   4                        MOTOROLA e32s      1
5   6  Acer Extensa Intel Core i3 11th Gen      1

In [117]:
popular_view_products = views.sort_values(by=['count'], ascending=False)
popular_view_products.head(10)

id                                pname  count
1   2                Samsung Galaxy M33 5G     23
3   4        HP 15s 12th Gen Intel Core i5     21
0   1             Samsung Galaxy S21 FE 5G     19
6   7      Symbol Men's Regular Polo Shirt     16
2   3                        MOTOROLA e32s     15
7   8           Nike Gravity Running Shoes     13
4   5       Hp 14S, 11Th Gen Intel Core I3     10
5   6  Acer Extensa Intel Core i3 11th Gen      4

As there is 3 models we used for picking products. We prioritized each recommendation.

Priority 1 - Rating given by user is most important feedback for any product as he/she used the product and provided exact experience.

Priority 2 - Add to Cart which means user is willing to take the product based on the given specifications.

Priority 3 - View is not as important as user may or may not be interested in the product hence it is least prioritized.

In [118]:
recommended_products_ratings = []
data = titles_based_on_ratings[0]
for i in range(0, data.shape[0]):
    recommended_products_ratings.append(data[i].numpy().decode())

recommended_products_ratings

['Hp 14S, 11Th Gen Intel Core I3',
 'Samsung Galaxy M33 5G',
 'Samsung Galaxy S21 FE 5G',
 'MOTOROLA e32s',
 "Symbol Men's Regular Polo Shirt"]

In [119]:
def common_recommended_products(list1, list2):
    return list(set(list1) & set(list2))

In [120]:
recommended_products_util = common_recommended_products(recommended_products_ratings, popular_cart_products)
recommended_products = common_recommended_products(recommended_products_util, popular_view_products)

recommended_products = recommended_products + recommended_products_util
recommended_products = recommended_products + recommended_products_ratings

if len(recommended_products) > 5:
    extra_elements = len(recommended_products) - 5
    del recommended_products[-extra_elements]

recommended_products

['Hp 14S, 11Th Gen Intel Core I3',
 'Samsung Galaxy M33 5G',
 'Samsung Galaxy S21 FE 5G',
 'MOTOROLA e32s',
 "Symbol Men's Regular Polo Shirt"]

### Subsection Based Recommendations

In [123]:
statement = '''select * from store_rating'''
cursor.execute(statement)
ratings = cursor.fetchall()
ratings = pd.DataFrame(ratings)
print(ratings.shape)
ratings.columns = ['id', 'userid', 'subsection', 'pname', 'rating']
ratings.head()

(14, 5)


id  userid subsection                          pname  rating
0   1       1     Mobile          Samsung Galaxy M33 5G       4
1   2       3     Mobile                  MOTOROLA e32s       4
2   3       2     Mobile          Samsung Galaxy M33 5G       5
3   4       3     Mobile          Samsung Galaxy M33 5G       4
4   5       1     Laptop  HP 15s 12th Gen Intel Core i5       2

In [124]:
ratings['userid'] = ratings['userid'].apply(str)
ratings['rating'] = ratings['rating'].astype(float)

In [125]:
section = "Mobile"
ratings = ratings[ratings['subsection'] == section]
ratings

id userid subsection                     pname  rating
0   1      1     Mobile     Samsung Galaxy M33 5G     4.0
1   2      3     Mobile             MOTOROLA e32s     4.0
2   3      2     Mobile     Samsung Galaxy M33 5G     5.0
3   4      3     Mobile     Samsung Galaxy M33 5G     4.0
7   8      2     Mobile  Samsung Galaxy S21 FE 5G     5.0

In [126]:
ratings = ratings[['pname', 'userid', 'rating']]
ratings.head()

pname userid  rating
0     Samsung Galaxy M33 5G      1     4.0
1             MOTOROLA e32s      3     4.0
2     Samsung Galaxy M33 5G      2     5.0
3     Samsung Galaxy M33 5G      3     4.0
7  Samsung Galaxy S21 FE 5G      2     5.0

In [1]:
ratings_model.save_weights('./checkpoints/my_checkpoint')

NameError: name 'ratings_model' is not defined

In [152]:
model = ProductRatingModel(rating_weight=1.0, retrieval_weight=1.0)
model.compile(optimizer=tf.keras.optimizers.Adagrad(0.1))
model.load_weights('./checkpoints/my_checkpoint')
metrics = model.evaluate(cached_test, return_dict=True)
brute_force = tfrs.layers.factorized_top_k.BruteForce(model.user_model)
brute_force.index_from_dataset(products.batch(128).map(lambda title: (title, ratings_model.product_model(title))))

ValueError: in user code:

    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1557, in test_function  *
        return step_function(self, iterator)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1546, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1535, in run_step  **
        outputs = model.test_step(data)
    File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\models\base.py", line 88, in test_step
        loss = self.compute_loss(inputs, training=False)
    File "C:\Users\yashk\AppData\Local\Temp/ipykernel_6488/4186026065.py", line 37, in compute_loss
        retrieval_loss = self.retrieval_task(user_embeddings, product_embeddings)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_file67ei5xe9.py", line 81, in tf__call
        ag__.if_stmt(ag__.ld(compute_metrics), if_body_2, else_body_2, get_state_2, set_state_2, (), 0)
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_file67ei5xe9.py", line 64, in if_body_2
        ag__.if_stmt(ag__.ld(self)._factorized_metrics, if_body, else_body, get_state, set_state, (), 0)
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_file67ei5xe9.py", line 60, in if_body
        ag__.converted_call(ag__.ld(metric_update_ops).append, (ag__.converted_call(ag__.ld(self)._factorized_metrics.update_state, (ag__.ld(query_embeddings), ag__.ld(candidate_embeddings)), None, fscope),), None, fscope)
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_file93chvymw.py", line 21, in tf__update_state
        (top_k_predictions, _) = ag__.converted_call(ag__.ld(self)._candidates, (ag__.ld(query_embeddings),), dict(k=ag__.ld(self)._k), fscope)
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_fileaz5o9aag.py", line 163, in tf__call
        results = ag__.converted_call(ag__.converted_call(ag__.ld(candidates).map, (ag__.ld(top_scores),), dict(num_parallel_calls=ag__.ld(self)._num_parallel_calls), fscope).reduce, (ag__.ld(initial_state), ag__.ld(top_k)), None, fscope)
    File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_fileaz5o9aag.py", line 48, in top_scores
        scores = ag__.converted_call(ag__.ld(self)._compute_score, (ag__.ld(queries), ag__.ld(candidate_batch)), None, fscope_1)
    File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\layers\factorized_top_k.py", line 319, in _compute_score
        return tf.matmul(queries, candidates, transpose_b=True)

    ValueError: Exception encountered when calling layer "retrieval_6" (type Retrieval).
    
    in user code:
    
        File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\tasks\retrieval.py", line 143, in call  *
            metric_update_ops.append(
        File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\metrics\factorized_top_k.py", line 84, in update_state  *
            top_k_predictions, _ = self._candidates(query_embeddings, k=self._k)
        File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
        File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_fileaz5o9aag.py", line 163, in tf__call
            results = ag__.converted_call(ag__.converted_call(ag__.ld(candidates).map, (ag__.ld(top_scores),), dict(num_parallel_calls=ag__.ld(self)._num_parallel_calls), fscope).reduce, (ag__.ld(initial_state), ag__.ld(top_k)), None, fscope)
        File "C:\Users\yashk\AppData\Local\Temp\__autograph_generated_fileaz5o9aag.py", line 48, in top_scores
            scores = ag__.converted_call(ag__.ld(self)._compute_score, (ag__.ld(queries), ag__.ld(candidate_batch)), None, fscope_1)
        File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\layers\factorized_top_k.py", line 319, in _compute_score
            return tf.matmul(queries, candidates, transpose_b=True)
    
        ValueError: Exception encountered when calling layer "streaming_6" (type Streaming).
        
        in user code:
        
            File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\layers\factorized_top_k.py", line 409, in top_scores  *
                scores = self._compute_score(queries, candidate_batch)
            File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_recommenders\layers\factorized_top_k.py", line 319, in _compute_score  **
                return tf.matmul(queries, candidates, transpose_b=True)
        
            ValueError: Shape must be rank 2 but is rank 1 for '{{node MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=true](MatMul/sequential_25/embedding_19/embedding_lookup/Identity_1, args_1)' with input shapes: [?,32], [32].
        
        
        Call arguments received by layer "streaming_6" (type Streaming):
          • queries=tf.Tensor(shape=(None, 32), dtype=float32)
          • k=100
    
    
    Call arguments received by layer "retrieval_6" (type Retrieval):
      • query_embeddings=tf.Tensor(shape=(None, 32), dtype=float32)
      • candidate_embeddings=tf.Tensor(shape=(None, 32), dtype=float32)
      • sample_weight=None
      • candidate_sampling_probability=None
      • candidate_ids=None
      • compute_metrics=True


In [153]:
_, titles_based_on_ratings = brute_force(np.array(["42"]), k = 5)
print(f"{titles_based_on_ratings[0]}")

[b'MOTOROLA e32s' b'Acer Extensa Intel Core i3 11th Gen'
 b'Nike Gravity Running Shoes' b'Hp 14S, 11Th Gen Intel Core I3'
 b"Symbol Men's Regular Polo Shirt"]


### Collaborative Filtering

In [121]:
import matplotlib.pyplot as plt
from sklearn.decomposition import TruncatedSVD

In [ ]:
ratings = pd.DataFrame(db['store_rating'].find())
ratings_with_id = ratings[['pname', 'userid', 'rating']]

Only product id and user rating is needed for this purpose

In [ ]:
popular_products = pd.DataFrame(ratings_with_id.groupby('product_id')['user_rating'].count())
most_popular = popular_products.sort_values('user_rating', ascending=False)
most_popular.head(10)

In [ ]:
most_popular.head(30).plot(kind='bar')

In [ ]:
ratings_utility_matrix = ratings_with_id.pivot_table(values='user_rating', index='user_id', columns='product_id', fill_Value=0)
ratings_utility_matrix.head()

In [ ]:
X = ratings_utility_matrix.T
X.head()

In [ ]:
X1 = X

In [ ]:
svd = TruncatedSVD(n_components=10)
decomposed_matrix = svd.fit_transform(X)
decomposed_matrix.shape

In [ ]:
correlation_matrix = np.corrcoef(decomposed_matrix)
correlation_matrix.shape

In [ ]:
product_ = 1    # get the product id of current user
product_titles = list(X.index)
product_id = product_titles.index(product_)
product_id

In [ ]:
correlation_product_id = correlation_matrix[product_id]
correlation_product_id.shape

In [ ]:
recommend = list(X.index[correlation_product_id > 0.90])
recommend.remove(product_)
recommend[0: 9]